# Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SMELLYCATDSV
    username: postgres
    password: fatec2020
    driver-class-name: org.postgresql.Driver
    platform: postgres

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

